name: event_app
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.2







dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0  
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_messaging: ^14.8.0
  firebase_storage: ^11.7.0  

  
  
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
 
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Logo.png"

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_18pt-Italic.ttf
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        

  
  
  
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - assets/banners/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
