// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn08TQvxMN3I1W5Tp9phFAUt4ZdAJgkVc',
    appId: '1:577855978564:android:be30658a597ba474f2d011',
    messagingSenderId: '577855978564',
    projectId: 'eventapp-9c406',
    storageBucket: 'eventapp-9c406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5I6t-nkFByNK7irE3qvSemvZDAo3qLS8',
    appId: '1:577855978564:ios:dfc84b75c8171b12f2d011',
    messagingSenderId: '577855978564',
    projectId: 'eventapp-9c406',
    storageBucket: 'eventapp-9c406.firebasestorage.app',
    androidClientId: '577855978564-c9d2gj7ocunlga9pvcdo2mj6ggi06rbc.apps.googleusercontent.com',
    iosClientId: '577855978564-4gnse8ebt3i58o9e685fkachjd2rtgnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );
}
